M48
; DRILL file {KiCad 6.0.11-2627ca5db0~126~ubuntu20.04.1} date Thu 16 Feb 2023 11:57:48 CET
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-02-16T11:57:48+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.11-2627ca5db0~126~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.889
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X121.91Y-118.15
X127.69Y-118.15
T2
X128.851Y-94.53
X131.849Y-94.53
T3
X107.45Y-90.1
X167.5Y-90.1
T0
M30
